export const FILE_MESSAGES = {
    UPLOAD_URL_SUCCESS: 'Upload URL generated successfully.',
    INVALID_INPUT: 'File name and file type are required.',
    UPLOAD_URL_ERROR: 'Failed to generate upload URL.',
    FILES_RETRIEVED_SUCCESS: 'Files retrieved successfully.',
    FILE_METADATA_SUCCESS: 'File metadata retrieved successfully.',
    FILE_METADATA_NOT_FOUND: 'File metadata not found.',
    FILE_DELETE_SUCCESS: 'File deleted successfully.',
    FILE_DELETE_FAILED: 'Failed to delete file.',
    FILE_UPDATE_METADATA_SUCCESS: 'File metadata updated successfully.',
    FILE_UPDATE_METADATA_FAILED: 'Failed to update file metadata.',
    FILE_SEARCH_SUCCESS: 'File search completed successfully.',
    FILE_SEARCH_FAILED: 'Failed to perform file search.',
    DOWNLOAD_URL_SUCCESS: 'Download URL generated successfully.',
    DOWNLOAD_URL_FAILED: 'Failed to generate download URL.',
    UPLOAD_FINALIZE_SUCCESS: 'File upload finalized successfully.',
    UPLOAD_FINALIZE_FAILED: 'Failed to finalize file upload.',
    SHARE_LINK_SUCCESS: 'File share link generated successfully.',
    SHARE_LINK_FAILED: 'Failed to generate file share link.',
  };
  